CREATE TABLE `ubigeo_peru_2016`.`provincias` ( `id` INT NOT NULL AUTO_INCREMENT , `id_dep` INT NOT NULL , `ubigeo` VARCHAR NOT NULL , `name` VARCHAR NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0101', 'Chachapoyas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0102', 'Bagua');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0103', 'Bongará');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0104', 'Condorcanqui');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0105', 'Luya');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0106', 'Rodríguez de Mendoza');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 01,	'0107', 'Utcubamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0201', 'Huaraz');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0202', 'Aija');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0203', 'Antonio Raymondi');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0204', 'Asunción');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0205', 'Bolognesi');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0206', 'Carhuaz');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0207', 'Carlos Fermín Fitzcarrald');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0208', 'Casma');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0209', 'Corongo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0210', 'Huari');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0211', 'Huarmey');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0212', 'Huaylas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0213', 'Mariscal Luzuriaga');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0214', 'Ocros');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0215', 'Pallasca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0216', 'Pomabamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0217', 'Recuay');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0218', 'Santa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0219', 'Sihuas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 02,	'0220', 'Yungay');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0301', 'Abancay');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0302', 'Andahuaylas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0303', 'Antabamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0304', 'Aymaraes');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0305', 'Cotabambas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0306', 'Chincheros');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 03,	'0307', 'Grau');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0401', 'Arequipa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0402', 'Camaná');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0403', 'Caravelí');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0404', 'Castilla');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0405', 'Caylloma');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0406', 'Condesuyos');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0407', 'Islay');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 04,	'0408', 'La Uniòn');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0501', 'Huamanga');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0502', 'Cangallo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0503', 'Huanca Sancos');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0504', 'Huanta');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0505', 'La Mar');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0506', 'Lucanas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0507', 'Parinacochas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0508', 'Pàucar del Sara Sara');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0509', 'Sucre');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0510', 'Víctor Fajardo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 05,	'0511', 'Vilcas Huamán');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0601', 'Cajamarca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0602', 'Cajabamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0603', 'Celendín');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0604', 'Chota');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0605', 'Contumazá');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0606', 'Cutervo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0607', 'Hualgayoc');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0608', 'Jaén');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0609', 'San Ignacio');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0610', 'San Marcos');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0611', 'San Miguel');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0612', 'San Pablo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 06,	'0613', 'Santa Cruz');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 07,	'0701', 'Prov. Const. del Callao');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0801', 'Cusco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0802', 'Acomayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0803', 'Anta');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0804', 'Calca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0805', 'Canas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0806', 'Canchis');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0807', 'Chumbivilcas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0808', 'Espinar');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0809', 'La Convención');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0810', 'Paruro');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0811', 'Paucartambo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0812', 'Quispicanchi');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 08,	'0813', 'Urubamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0901', 'Huancavelica');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0902', 'Acobamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0903', 'Angaraes');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0904', 'Castrovirreyna');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0905', 'Churcampa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0906', 'Huaytará');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 09,	'0907', 'Tayacaja');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1001', 'Huánuco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1002', 'Ambo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1003', 'Dos de Mayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1004', 'Huacaybamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1005', 'Huamalíes');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1006', 'Leoncio Prado');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1007', 'Marañón');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1008', 'Pachitea');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1009', 'Puerto Inca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1010', 'Lauricocha');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 10,	'1011', 'Yarowilca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 11,	'1101', 'Ica');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 11,	'1102', 'Chincha');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 11,	'1103', 'Nasca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 11,	'1104', 'Palpa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 11,	'1105', 'Pisco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1201', 'Huancayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1202', 'Concepción');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1203', 'Chanchamayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1204', 'Jauja');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1205', 'Junín');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1206', 'Satipo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1207', 'Tarma');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1208', 'Yauli');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 12,	'1209', 'Chupaca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1301', 'Trujillo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1302', 'Ascope');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1303', 'Bolívar');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1304', 'Chepén');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1305', 'Julcán');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1306', 'Otuzco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1307', 'Pacasmayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1308', 'Pataz');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1309', 'Sánchez Carrión');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1310', 'Santiago de Chuco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1311', 'Gran Chimú');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 13,	'1312', 'Virú');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 14,	'1401', 'Chiclayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 14,	'1402', 'Ferreñafe');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 14,	'1403', 'Lambayeque');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1501', 'Lima');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1502', 'Barranca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1503', 'Cajatambo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1504', 'Canta');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1505', 'Cañete');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1506', 'Huaral');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1507', 'Huarochirí');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1508', 'Huaura');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1509', 'Oyón');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 15,	'1510', 'Yauyos');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1601', 'Maynas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1602', 'Alto Amazonas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1603', 'Loreto');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1604', 'Mariscal Ramón Castilla');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1605', 'Requena');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1606', 'Ucayali');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1607', 'Datem del Marañón');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 16,	'1608', 'Putumayo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 17,	'1701', 'Tambopata');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 17,	'1702', 'Manu');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 17,	'1703', 'Tahuamanu');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 18,	'1801', 'Mariscal Nieto');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 18,	'1802', 'General Sánchez Cerro');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 18,	'1803', 'Ilo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 19,	'1901', 'Pasco');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 19,	'1902', 'Daniel Alcides Carrión');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 19,	'1903', 'Oxapampa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2001', 'Piura');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2002', 'Ayabaca');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2003', 'Huancabamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2004', 'Morropón');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2005', 'Paita');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2006', 'Sullana');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2007', 'Talara');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 20,	'2008', 'Sechura');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2101', 'Puno');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2102', 'Azángaro');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2103', 'Carabaya');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2104', 'Chucuito');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2105', 'El Collao');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2106', 'Huancané');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2107', 'Lampa');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2108', 'Melgar');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2109', 'Moho');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2110', 'San Antonio de Putina');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2111', 'San Román');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2112', 'Sandia');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 21,	'2113', 'Yunguyo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2201', 'Moyobamba');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2202', 'Bellavista');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2203', 'El Dorado');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2204', 'Huallaga');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2205', 'Lamas');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2206', 'Mariscal Cáceres');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2207', 'Picota');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2208', 'Rioja');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2209', 'San Martín');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 22,	'2210', 'Tocache');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 23,	'2301', 'Tacna');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 23,	'2302', 'Candarave');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 23,	'2303', 'Jorge Basadre');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 23,	'2304', 'Tarata');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 24,	'2401', 'Tumbes');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 24,	'2402', 'Contralmirante Villar');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 24,	'2403', 'Zarumilla');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 25,	'2501', 'Coronel Portillo');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 25,	'2502', 'Atalaya');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 25,	'2503', 'Padre Abad');
INSERT INTO `provincias` (`id`, `id_dep`, `ubigeo`, `name`) VALUES ( NULL, 25,	'2504', 'Purús');
